import type { Command, Option } from 'commander';
import type { Context } from './context.ts';
import {
  createProgram,
  ENVIRONMENT_HELP,
  EXIT_CODES_HELP,
  SCHEMA_ALIASES,
} from './program.ts';

function fullName(command: Command): string {
  const names: string[] = [];
  for (
    let current: Command | null = command;
    current;
    current = current.parent
  ) {
    names.unshift(current.name());
  }

  return names.join(' ');
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function anchor(name: string): string {
  return name.replace(/\s+/g, '-').toLowerCase();
}

function describeCommand(command: Command): string {
  const alias = SCHEMA_ALIASES[fullName(command).replace(/^jsonpad /, '')];
  if (alias) {
    return [
      `### \`${fullName(command)}\``,
      '',
      `The same as [\`jsonpad ${alias}\`](#${anchor(`jsonpad ${alias}`)}), with the same arguments and options.`,
    ].join('\n');
  }

  const lines = [
    `### \`${fullName(command)}\``,
    '',
    command.description(),
    '',
    '```',
    `${fullName(command)} ${command.usage()}`,
    '```',
  ];

  if (command.registeredArguments.length > 0) {
    lines.push('', '| Argument | Description |', '| --- | --- |');
    for (const argument of command.registeredArguments) {
      const name = `${argument.name()}${argument.variadic ? '...' : ''}`;
      const defaultValue =
        argument.defaultValue !== undefined
          ? ` (default: \`${argument.defaultValue}\`)`
          : '';
      lines.push(
        `| \`${name}\`${argument.required ? '' : ' (optional)'} | ${escapeCell(
          argument.description
        )}${defaultValue} |`
      );
    }
  }

  const options = command.options.filter(option => option.long !== '--help');
  if (options.length > 0) {
    lines.push('', ...optionsTable(options));
  }

  return lines.join('\n');
}

function optionsTable(options: readonly Option[]): string[] {
  return [
    '| Option | Description |',
    '| --- | --- |',
    ...options.map(option => {
      const choices = option.argChoices
        ? ` (one of: ${option.argChoices.join(', ')})`
        : '';

      return `| \`${option.flags}\` | ${escapeCell(option.description)}${choices} |`;
    }),
  ];
}

/**
 * Help text with its heading removed and its indentation undone
 */
function helpSection(help: string): string {
  return help
    .split('\n')
    .slice(1)
    .map(line => line.replace(/^  /, ''))
    .join('\n');
}

function commandsIn(command: Command): Command[] {
  return command.commands.flatMap(child =>
    child.commands.length > 0 ? commandsIn(child) : [child]
  );
}

/**
 * Generate the command reference as Markdown, from the command definitions
 */
export function generateReference(context: Context): string {
  const program = createProgram(context);
  const commands = commandsIn(program);

  return `${[
    '# jsonpad command reference',
    '',
    "<!-- Generated by `npm run reference` from the command definitions. Don't edit this file by hand. -->",
    '',
    'Run `jsonpad <command> --help` for the same information in a terminal.',
    '',
    '## Commands',
    '',
    ...commands.map(
      command =>
        `- [\`${fullName(command)}\`](#${anchor(fullName(command))}): ${command.summary() || command.description()}`
    ),
    '',
    ...commands.flatMap(command => [describeCommand(command), '']),
    '## Global options',
    '',
    'Every command accepts these.',
    '',
    ...optionsTable(program.options.filter(option => option.long !== '--help')),
    '',
    '## Environment',
    '',
    '```',
    helpSection(ENVIRONMENT_HELP),
    '```',
    '',
    '## Exit codes',
    '',
    '```',
    helpSection(EXIT_CODES_HELP),
    '```',
  ].join('\n')}\n`;
}
